name: vdi_system_admin

services:
  postgres:
    image: postgres:17.6
    container_name: vdi_admin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vdi_admin
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: vdi_postgres
    ports:
      - "5432:5432"
    volumes:
      - vdi_admin_postgres:/var/lib/postgresql/data
    networks:
      - vdi_network

  influxdb:
    image: influxdb:2.7.12
    container_name: vdi_influx_db
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - vdi_network

  kafka:
    image: apache/kafka:4.1.0
    container_name: vdi_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    networks:
      - vdi_network

  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vdi_system_admin_app
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - vdi_network
    depends_on:
      - postgres
      - influxdb

volumes:
  vdi_admin_postgres:
  influxdb_data:

networks:
  vdi_network:
    driver: bridge
